name: Python Flask CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd Diagram-Magix
          git pull
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          export DIAGRAM_API=${{ secrets.DIAGRAM_API }}
          export EXTERNAL_DIAGRAM_API=${{ secrets.EXTERNAL_DIAGRAM_API }}
          docker-compose down || true
          docker-compose build \
            --build-arg OPENAI_API_KEY=${OPENAI_API_KEY} \
            --build-arg DIAGRAM_API=${DIAGRAM_API} \
            --build-arg EXTERNAL_DIAGRAM_API=${EXTERNAL_DIAGRAM_API}
          docker-compose up -d

